routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Admin')->group(function(){
	Route::get('sign-in','LoginController@getLogin')->middleware('loginal')->name('getLogin');
	Route::post('sign-in','LoginController@postLogin')->name('postLogin');
	Route::get('logout','LoginController@getLogout')->name('getLogout');

	Route::get('forgot-password', 'ResetPasswordController@getPassword')->name('getPassword');
	Route::post('forgot-password', 'ResetPasswordController@sendEmail')->name('sendEmail');
	Route::get('change-new-password', 'ResetPasswordController@getNewPassword')->name('getNewPassword');
	Route::post('change-new-password', 'ResetPasswordController@postNewPassword')->name('postNewPassword');
});
Route::namespace('Frontend')->group(function() {
	Route::get('','HomeController@index')->name('home');
	Route::get('bao-hiem-nhan-tho-cho-be-tre-em-con-tre-so-sinh','HomeController@GetBHNT')->name('bao-hiem-nhan-tho-cho-be-tre-em-con-tre-so-sinh');
	
	Route::get('gioi-thieu','HomeController@gioithieu')->name('gioi-thieu');
	Route::get('lien-he','HomeController@Getlienhe')->name('lien-he');
	Route::post('lien-he','HomeController@Postlienhe')->name('lien-he');
	Route::get('dieu-khoan-dich-vu','HomeController@dieukhoandichvu')->name('dieu-khoan-dich-vu');
	Route::get('chinh-sach-bao-mat','HomeController@chinhsachbaomat')->name('chinh-sach-bao-mat');
	Route::get('tu-van-mien-phi','HomeController@GetTuvan')->name('tu-van-mien-phi');
	Route::post('tu-van-mien-phi','HomeController@PostTuvan')->name('tu-van-mien-phi');
	Route::get('bai-viet','HomeController@GetNews')->name('bai-viet');
	Route::get('bai-viet-detail/{slug}','HomeController@GetNewsDetail')->name('bai-viet-detail');

	Route::post('tim-kiem','HomeController@search');
	
});

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){

	Route::get('dashboard','HomeController@index')->name('dashboard');

	Route::prefix('useradmin')->name('useradmin.')->group(function(){
		Route::get('index','UseradminController@index')->name('index');

		Route::get('add','UseradminController@create')->name('create');
		Route::post('add','UseradminController@store')->name('store');

		Route::get('edit/{id}','UseradminController@edit')->name('edit');
		Route::post('edit/{id}','UseradminController@update')->name('update');

		Route::get('change-password','UseradminController@Getchangepass')->name('change-password');
		Route::post('change-password','UseradminController@Postchangepass');

		Route::get('delete/{id}','UseradminController@destroy')->name('destroy');
	});
	Route::prefix('menu')->name('menu.')->group(function(){
		Route::get('index','MenuController@index')->name('index');

		Route::get('add','MenuController@create')->name('create');
		Route::post('add','MenuController@store')->name('store');

		Route::get('show-detail/{id}','MenuController@show')->name('show');

		Route::get('edit/{id}','MenuController@edit')->name('edit');
		Route::post('edit/{id}','MenuController@update')->name('update');

		Route::post('delete/{id}','MenuController@destroy')->name('destroy');
	});
	Route::prefix('lien-he')->name('lienhe.')->group(function(){
		Route::get('index','LienheController@index')->name('index');

		Route::get('add','LienheController@create')->name('create');
		Route::post('add','LienheController@store')->name('store');

		Route::get('show-detail/{id}','LienheController@show')->name('show');

		Route::get('edit/{id}','LienheController@edit')->name('edit');
		Route::post('edit/{id}','LienheController@update')->name('update');
		
		Route::post('delete/{id}','LienheController@destroy')->name('destroy');
	});
	Route::prefix('FAQ')->name('faq.')->group(function(){
		Route::get('index','FAQController@index')->name('index');

		Route::get('add','FAQController@create')->name('create');
		Route::post('add','FAQController@store')->name('store');

		Route::get('show-detail/{id}','FAQController@show')->name('show');

		Route::get('edit/{id}','FAQController@edit')->name('edit');
		Route::post('edit/{id}','FAQController@update')->name('update');
		
		Route::post('delete/{id}','FAQController@destroy')->name('destroy');
	});
	Route::prefix('tin-tuc')->name('news.')->group(function(){
		Route::get('index','NewsController@index')->name('index');

		Route::get('add','NewsController@create')->name('create');
		Route::post('add','NewsController@store')->name('store');

		Route::get('show-detail/{id}','NewsController@show')->name('show');

		Route::get('edit/{id}','NewsController@edit')->name('edit');
		Route::post('edit/{id}','NewsController@update')->name('update');
		
		Route::post('delete/{id}','NewsController@destroy')->name('destroy');
	});
	Route::prefix('client')->name('client.')->group(function(){
		Route::get('index','ClientController@index')->name('index');

		Route::get('add','ClientController@create')->name('create');
		Route::post('add','ClientController@store')->name('store');

		Route::get('show-detail/{id}','ClientController@show')->name('show');

		Route::get('edit/{id}','ClientController@edit')->name('edit');
		Route::post('edit/{id}','ClientController@update')->name('update');
		
		Route::post('delete/{id}','ClientController@destroy')->name('destroy');
	});
	
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
});

app/Http/Controllers/Admin/UseradminController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\Useradmins\StoreRequest;
use App\Http\Controllers\Controller;
use App\Model\Useradmin;
use Input;
use DB,Hash,Auth;
use DateTime;

class UseradminController extends Controller
{
    private $useradmin;


    public function __construct(Useradmin $useradmin)
    {
        $this->useradmin          = $useradmin;

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function Getchangepass()
    {
        return view('admin.module.useradmin.user-changepass');
    }
     public function Postchangepass(Request $request)
    {
        if (!(Hash::check($request->currentpassword, Auth::user()->password))) {
            // Mật khẩu trùng khớp
            return redirect()->back()->with("error","Mật khẩu hiện tại của bạn không khớp với mật khẩu bạn cung cấp. Vui lòng thử lại.");
        }
        if($request->newpassword != $request->newpassword_confirmation) {
            //Mật khẩu hiện tại và mật khẩu mới giống nhau
            return redirect()->back()->with("error","Mật khẩu mới không thể giống như mật khẩu hiện tại của bạn. Vui lòng chọn một mật khẩu khác nhau.");
        }

        $validatedData = $request->validate([
            'currentpassword' => 'required',
            'newpassword' => 'required|min:6|confirmed',
        ]);
        // Đổi mật khẩu
        
        $data =  array('password' =>bcrypt($request->newpassword));
         
         // dd($data);
        
         DB::table('bh_admin')->whereId(Auth::user()->id)->update($data);

         echo "<script>
                alert('Mật khẩu của bạn đã được thay đổi thành công.');
                window.location = '".url('/admin/dashboard')."'
              </script>";
    }

    public function index()
    {
        $data['useradmin']   = $this->useradmin->ListAdmin();
        return view('admin.module.useradmin.user-list',$data);    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.module.useradmin.user-create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $req)
    {
        try {
            $data = array(
                        'username' => $req->username,
                        'password' => bcrypt($req->password),
                        'role' => $req->role,
                        'fullname' => $req->fullname,
                        'email' =>$req->email,
                        'created_at'    => new DateTime,
                    ); 
                
        $this->useradmin->storeAdmin($data);
        } catch (Exception $e) {
            return back()->with('alerterr','Wrong format');
        }
        
            return redirect()->back()->with('alertsuc','Thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['useradmin'] = $this->useradmin->getUser($id);
        return view('admin.module.useradmin.user-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        try {
            $data = array(
                        'role' => $req->role,
                        'fullname' => $req->fullname,
                        'username'  => $req->username,
                        'email' =>$req->email,
                        'password' => bcrypt($req->password),
                        'updated_at'    => new DateTime,
                    ); 
                
        $this->useradmin->updateUser($data,$id);
        } catch (Exception $e) {
             return back()->with('alerterr','Wrong format');
        }
            return redirect()->back()->with('alertsuc','Thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       
        $result = $this->useradmin->delAdmin($id);

        if($result){
            return redirect()->route('useradmin.index')->with('alertsuc','Xóa user thành công');
         } else{
             return redirect()->route('useradmin.index')->with('alerterr','Vui lòng không xóa admin tổng');
         }    
    }
}

resources/views/admin/module/useradmin/user-changepass.blade.php
@extends('admin.welcome')
@section('title','Change Password')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('useradmin.index')}}" class="breadcrumb-item">List Admin</a>
                <span class="breadcrumb-item active">Change Password</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">           
            <div class="card-body">
                <form class="form-validate-jquery" action="" method="POST" enctype="multipart/form-data">
                    @csrf
                    <fieldset class="mb-3">
                        <legend class="text-uppercase font-size-sm font-weight-bold">Change Password</legend>

                         <!-- Password field -->
                        <div class="form-group row">
                            <label class="col-form-label col-lg-3">Old Password<span class="text-danger">*</span></label>
                            <div class="col-lg-4">
                                <input type="password" name="currentpassword" id="password" class="form-control" required="" />
                            </div>
                        </div>
                        <!-- /password field -->

                        <!-- Password field -->
                        <div class="form-group row">
                            <label class="col-form-label col-lg-3">New Password<span class="text-danger">*</span></label>
                            <div class="col-lg-4">
                                <input type="password" name="newpassword" id="password" class="form-control" required placeholder="Minimum 6 characters allowed"/>
                            </div>
                        </div>
                        <!-- /password field -->

                        <!-- Repeat password -->
                        <div class="form-group row">
                           <label class="col-form-label col-lg-3">Enter a new password<span class="text-danger">*</span></label>
                           <div class="col-lg-4">
                               <input type="password" name="newpassword_confirmation" class="form-control" required placeholder="Try different password"/>
                           </div>
                       </div>
                        <!-- /repeat password -->

                    </fieldset>

                    <div class="d-flex justify-content-center align-items-center" style="margin-right: 260px">
                        <button type="submit" class="btn btn-primary ml-4">Change<i class="icon-paperplane ml-2"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/useradmin/user-create.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('useradmin.index')}}" class="breadcrumb-item">List Admin</a>
                <span class="breadcrumb-item active">Add</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Add administrator</h5>                
            </div>
            <div class="card-body">
                <form action="{{ route('useradmin.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Fullname <span class="text-danger">*</span></label>
                            <input value="{{old('fullname')}}" type="text" name="fullname" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Username <span class="text-danger">*</span></label>
                            <input value="{{old('username')}}" type="text" name="username" class="form-control" required="">
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Email <span class="text-danger">*</span></label>
                            <input value="{{old('email')}}" type="text" name="email" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Password <span class="text-danger">*</span></label>
                            <input value="{{old('password')}}" type="password" name="password" class="form-control" required="">
                        </div> 
                    </div>
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Role <span class="text-danger">*</span></label>
                            <select name="role" class="form-control pro-edt-select form-control-primary">
                                <option value='0' selected="">Admin</option>
                                    <option value='1'>Technical</option>                                                          
                            </select>
                        </div>
                    </div>
                    <div class="form-group text-center">
                        <button name="button" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Save
                        </button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/useradmin/user-edit.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('useradmin.index')}}" class="breadcrumb-item">List Admin</a>
                <span class="breadcrumb-item active">Edit</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Update administrator</h5>                
            </div>
            <div class="card-body">
                <form action="{{route('useradmin.update', ['sanpham' => $useradmin->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Fullname <span class="text-danger">*</span></label>
                            <input value="{{old('fullname',$useradmin->fullname)}}" type="text" name="fullname" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Username <span class="text-danger">*</span></label>
                            <input value="{{old('username',$useradmin->username)}}" type="text" name="username" class="form-control" >
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Email <span class="text-danger">*</span></label>
                            <input value="{{old('email',$useradmin->email)}}" type="text" name="email" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Password <span class="text-danger">*</span></label>
                            <input value="{{old('password')}}" type="password" name="password" class="form-control" >
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Role <span class="text-danger">*</span></label>
                            <select name="role" class="form-control pro-edt-select form-control-primary">
                                <option value='0' {{$useradmin->role == 0 ? 'selected' : ''}}>Admin</option>
                                <option value='1' {{$useradmin->role == 1 ? 'selected' : ''}}>Technical</option>                                        
                            </select>
                        </div>
                    </div>
                    <div class="form-group text-center">
                      
                        <button name="addProduct" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Update
                            </button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>


@endsection

resources/views/admin/module/useradmin/user-list.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('useradmin.index')}}" class="breadcrumb-item">List Admin</a>
                {{-- <span class="breadcrumb-item active">Current</span> --}}
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="content-wrapper">
    @include('admin.blocks.alert')
    <div class="content">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">List of administrators</h5>                
            </div>
            <div class="card-body">
                <div class="product-status-wrap">
                    <div class="form-group">
                        <a class="btn btn-success" href="{{ route('useradmin.create') }}">ADD</a>
                    </div>
                        <div class="table-responsive-sm form-group">
                            <table class="table table-sm table-striped table-bordered">
                                <thead>
                                    <tr >
                                        {{-- <th scope="col">
                                            <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                                        </th> --}}
                                        <th scope="col">ID</th>
                                        <th scope="col">Fullname</th>
                                        <th scope="col">Username</th>
                                        <th scope="col">Staff type</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Created date</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($useradmin as $item)
                                    <tr>
                                       {{--  <td >
                                            <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                                        </td> --}}
                                        <td>{{$item->id}}</td>
                                        <td>{{$item->fullname}}</td>
                                        <td>{{$item->username}}</td>
                                        <td>
                                            @if($item->role==0)
                                                <span class="badge badge-danger">Admin</span>
                                                
                                            @elseif($item->role==1)
                                                <span class="badge badge-success">Technical</span>    
                                            @endif
                                        </td>
                                        <td>{{$item->email}}</td>
                                        <td>{{ date("d/m/Y-H:i:s",strtotime($item ->created_at))}}</td>
                                        <td style="text-align: center;">
                                            <a href="{{ route('useradmin.edit', ['useradmin' => $item->id]) }}" data-toggle="tooltip" title="Edit" class="pd-setting-ed">
                                                <i class="icon-pencil7" aria-hidden="true"></i>
                                            </a>  &nbsp; &nbsp;

                                             <a href="{{ route('useradmin.destroy',['useradmin' => $item->id]) }}" onClick="return xacnhan('Bạn có chắc chắn muốn xóa ?');" class="list-icons-item text-danger-600" title="Delete">
                                                <i class="icon-trash"></i>
                                             </a>
                                        </td>                   
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group row">
                            <div style="position: absolute;right: 20px">
                                {{$useradmin->links()}}
                            </div>
                        </div>                     
                </div>
            </div>
        </div>
    </div>
</div>
@endsection