routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Admin')->group(function(){
	Route::get('sign-in','LoginController@getLogin')->middleware('loginal')->name('getLogin');
	Route::post('sign-in','LoginController@postLogin')->name('postLogin');
	Route::get('logout','LoginController@getLogout')->name('getLogout');

	Route::get('forgot-password', 'ResetPasswordController@getPassword')->name('getPassword');
	Route::post('forgot-password', 'ResetPasswordController@sendEmail')->name('sendEmail');
	Route::get('change-new-password', 'ResetPasswordController@getNewPassword')->name('getNewPassword');
	Route::post('change-new-password', 'ResetPasswordController@postNewPassword')->name('postNewPassword');
});
Route::namespace('Frontend')->group(function() {
	Route::get('','HomeController@index')->name('home');
	Route::get('bao-hiem-nhan-tho-cho-be-tre-em-con-tre-so-sinh','HomeController@GetBHNT')->name('bao-hiem-nhan-tho-cho-be-tre-em-con-tre-so-sinh');
	
	Route::get('gioi-thieu','HomeController@gioithieu')->name('gioi-thieu');
	Route::get('lien-he','HomeController@Getlienhe')->name('lien-he');
	Route::post('lien-he','HomeController@Postlienhe')->name('lien-he');
	Route::get('dieu-khoan-dich-vu','HomeController@dieukhoandichvu')->name('dieu-khoan-dich-vu');
	Route::get('chinh-sach-bao-mat','HomeController@chinhsachbaomat')->name('chinh-sach-bao-mat');
	Route::get('tu-van-mien-phi','HomeController@GetTuvan')->name('tu-van-mien-phi');
	Route::post('tu-van-mien-phi','HomeController@PostTuvan')->name('tu-van-mien-phi');
	Route::get('bai-viet','HomeController@GetNews')->name('bai-viet');
	Route::get('bai-viet-detail/{slug}','HomeController@GetNewsDetail')->name('bai-viet-detail');

	Route::post('tim-kiem','HomeController@search');
	
});

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){

	Route::get('dashboard','HomeController@index')->name('dashboard');

	Route::prefix('useradmin')->name('useradmin.')->group(function(){
		Route::get('index','UseradminController@index')->name('index');

		Route::get('add','UseradminController@create')->name('create');
		Route::post('add','UseradminController@store')->name('store');

		Route::get('edit/{id}','UseradminController@edit')->name('edit');
		Route::post('edit/{id}','UseradminController@update')->name('update');

		Route::get('change-password','UseradminController@Getchangepass')->name('change-password');
		Route::post('change-password','UseradminController@Postchangepass');

		Route::get('delete/{id}','UseradminController@destroy')->name('destroy');
	});
	Route::prefix('menu')->name('menu.')->group(function(){
		Route::get('index','MenuController@index')->name('index');

		Route::get('add','MenuController@create')->name('create');
		Route::post('add','MenuController@store')->name('store');

		Route::get('show-detail/{id}','MenuController@show')->name('show');

		Route::get('edit/{id}','MenuController@edit')->name('edit');
		Route::post('edit/{id}','MenuController@update')->name('update');

		Route::post('delete/{id}','MenuController@destroy')->name('destroy');
	});
	Route::prefix('lien-he')->name('lienhe.')->group(function(){
		Route::get('index','LienheController@index')->name('index');

		Route::get('add','LienheController@create')->name('create');
		Route::post('add','LienheController@store')->name('store');

		Route::get('show-detail/{id}','LienheController@show')->name('show');

		Route::get('edit/{id}','LienheController@edit')->name('edit');
		Route::post('edit/{id}','LienheController@update')->name('update');
		
		Route::post('delete/{id}','LienheController@destroy')->name('destroy');
	});
	Route::prefix('FAQ')->name('faq.')->group(function(){
		Route::get('index','FAQController@index')->name('index');

		Route::get('add','FAQController@create')->name('create');
		Route::post('add','FAQController@store')->name('store');

		Route::get('show-detail/{id}','FAQController@show')->name('show');

		Route::get('edit/{id}','FAQController@edit')->name('edit');
		Route::post('edit/{id}','FAQController@update')->name('update');
		
		Route::post('delete/{id}','FAQController@destroy')->name('destroy');
	});
	Route::prefix('tin-tuc')->name('news.')->group(function(){
		Route::get('index','NewsController@index')->name('index');

		Route::get('add','NewsController@create')->name('create');
		Route::post('add','NewsController@store')->name('store');

		Route::get('show-detail/{id}','NewsController@show')->name('show');

		Route::get('edit/{id}','NewsController@edit')->name('edit');
		Route::post('edit/{id}','NewsController@update')->name('update');
		
		Route::post('delete/{id}','NewsController@destroy')->name('destroy');
	});
	Route::prefix('client')->name('client.')->group(function(){
		Route::get('index','ClientController@index')->name('index');

		Route::get('add','ClientController@create')->name('create');
		Route::post('add','ClientController@store')->name('store');

		Route::get('show-detail/{id}','ClientController@show')->name('show');

		Route::get('edit/{id}','ClientController@edit')->name('edit');
		Route::post('edit/{id}','ClientController@update')->name('update');
		
		Route::post('delete/{id}','ClientController@destroy')->name('destroy');
	});
	
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
});

resources/views/admin/blocks/alert.blade.php
@if(session('alertsuc'))
{{-- <section class="alert alert-success alert-st-one" role="alert">
    <i class="fa fa-check adminpro-checked-pro admin-check-pro" aria-hidden="true"></i>
        <p class="message-mg-rt">
            {{ session('alertsuc') }}
        </p>
</section> --}}
<{{-- div class="alert alert-success" role="alert">
  <p>This is a success alert—check it out!</p>
</div> --}}
<script type="text/javascript">
    $.jGrowl('{{ session('alertsuc') }}', {
        theme: 'bg-success alert-rounded',
        life: 5000
    });
</script>
@endif
@if(session('alerterr'))
{{-- <section class="alert alert-danger alert-mg-b alert-st-four" role="alert">
    <i class="fa fa-window-close adminpro-danger-error admin-check-pro" aria-hidden="true"></i>
        <i class="fa fa-times adminpro-danger-error admin-check-pro" aria-hidden="true"></i>
        <p class="message-mg-rt">
            {{ session('alerterr') }}
        </p>
</section> --}}
<script type="text/javascript">
    $.jGrowl('{{ session('alerterr') }}', {
        theme: 'bg-danger alert-rounded',
        life: 5000
    });
</script>

@endif
@if(session('alerterrv2'))
<section class="alert alert-danger alert-mg-b" role="alert">
    <p style="font-weight: bold;">{{ session('alerterrv2') }}</p>
</section>
@endif
@if($errors->any())
<section class="alert alert-danger alert-mg-b" role="alert">
    @foreach ($errors->all() as $error)
        <span class="message-mg-rt">{{ $error }}</span><br>
    @endforeach
</section>
@endif
@if(session('alertwar'))
<script type="text/javascript">
   
            new Noty({
                layout: 'top',
                text: '{{session('alertwar')}}',
                type: 'success',
                theme: 'limitless',
                timeout: 10000
            }).show();  
    

</script>
@endif
@if(session('alertwar2'))
<div class="alert alert-info alert-success-style2 alert-success-stylenone">
    <i class="fa fa-info-circle adminpro-inform admin-check-sucess admin-check-pro-none" aria-hidden="true"></i>
    <p class="message-alert-none">{{ session('alertwar2') }}</p>
</div>
@endif
@if(session('alertsweet'))
<script type="text/javascript">
swal({
    // title: 'Good job!',
    html: '{!! session('alertsweet') !!}',
    type: 'success',
    buttonsStyling: false,
    confirmButtonClass: 'btn btn-primary',
    cancelButtonClass: 'btn btn-light'
});</script>
@endif

@if(session('alerterrbilling'))
<script type="text/javascript">
    swal({
          // title: 'Good job!',
          html: '<strong>{{session('alerterrbilling')}}</strong>',
          type: 'error',
          buttonsStyling: false,
          confirmButtonClass: 'btn btn-primary',
          cancelButtonClass: 'btn btn-light'
      });
</script>
@endif

@if (\Session::has('success'))
<div role="alert" id="flash-message">
    <div class="alert alert-success" >
      <h6 class="card-title">
        <p>Success</a>
      </h6>
    </div>
    {{-- <div id="collapsible-styled-group1" class="collapse show" style="">
      <div class="card-body">
          {!! __(\Session::get('success')) !!}
      </div>
    </div> --}}
</div>
@endif
<!-- --------------------error ----------------- -->
@if (\Session::has('error'))
<div role="alert" id="flash-message">
    <div class="card-header bg-danger">
      <h6 class="card-title">
        <a data-toggle="collapse" class="text-white" aria-expanded="true">Error</a>
      </h6>
    </div>
   {{--  <div id="collapsible-styled-group1" class="collapse show" style="">
      <div class="card-body">
          {!! __(\Session::get('error')) !!}
      </div>
    </div> --}}
</div>
@endif

resources/views/admin/blocks/footer.blade.php
<div class="navbar navbar-expand-lg navbar-light">
        <div class="text-center d-lg-none w-100">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-footer">
                <i class="icon-circle-down2"></i>
            </button>

        </div>

        <div class="navbar-collapse collapse" id="navbar-footer">
            <span class="navbar-text">
               &copy; 2019. <a href="#">Trang Quản Trị</a> Design by <a href="https://cloudone.vn/" target="_blank">CloudOne</a>
            </span>

            <ul class="navbar-nav ml-lg-auto">
                <li class="nav-item"><a class="navbar-nav-link" href="https://cloudone.vn/ve-chung-toi/">About</a></li>
                <li class="nav-item"><a class="navbar-nav-link" href="#">Terms</a></li>
                <li class="nav-item"><a class="navbar-nav-link" href="https://cloudone.vn/lien-he">Contact</a></li>
            </ul>
        </div>
    </div>

resources/views/admin/blocks/head.blade.php
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>@yield('title','Chào mừng bạn đến với trang quản trị website')</title>
	<link rel="shortcut icon" type="image/jpg" href="{{ asset('backend/global_assets/images/1044.png') }}"/>

	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="{{asset('backend/global_assets/css/icons/icomoon/styles.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('backend/global_assets/css/icons/fontawesome/styles.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('backend/global_assets/css/icons/material/icons.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('backend/assets/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('backend/assets/css/bootstrap_limitless.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('backend/assets/css/layout.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('backend/assets/css/components.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('backend/assets/css/colors.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('css/main.css')}}" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script src="{{asset('backend/global_assets/js/main/jquery.min.js')}}"></script>
	<script src="{{asset('backend/global_assets/js/main/bootstrap.bundle.min.js')}}"></script>
	<script src="{{asset('backend/global_assets/js/plugins/loaders/blockui.min.js')}}"></script>
	<script src="{{asset('js/myscript.js') }}"></script>
	<!-- /core JS files -->
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/css-toggle-switch@latest/dist/toggle-switch.css" />
	<script src="{{asset('backend/global_assets/js/plugins/forms/styling/uniform.min.js')}}"></script>
	
	<script src="{{asset('backend/global_assets/js/plugins/forms/selects/select2.min.js')}}"></script>
	<!-- Theme JS files -->
	<script src="{{asset('backend/assets/js/app.js')}}"></script>
	<!-- /theme JS files -->
	<script src="{{asset('backend/global_assets/js/demo_pages/form_actions.js')}}"></script>

	<script src="{{asset('backend/global_assets/js/plugins/notifications/jgrowl.min.js')}}"></script>
	<script src="{{asset('backend/global_assets/js/plugins/notifications/noty.min.js')}}"></script>
	<script src="{{asset('backend/global_assets/js/plugins/uploaders/fileinput/fileinput.min.js')}}"></script>

	<script src="{{asset('backend/global_assets/js/plugins/forms/styling/uniform.min.js')}}"></script>
	<script src="{{asset('backend/global_assets/js/plugins/forms/styling/switchery.min.js')}}"></script>
	<script src="{{asset('backend/global_assets/js/plugins/forms/styling/switch.min.js')}}"></script>

	<script src="{{asset('backend/global_assets/js/demo_pages/form_checkboxes_radios.js')}}"></script>

resources/views/admin/blocks/menu.blade.php
<div class="sidebar sidebar-light sidebar-main sidebar-expand-md align-self-start">
    <!-- Sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        Main sidebar
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->
    <!-- Sidebar content -->
    <div class="sidebar-content">
        <div class="card card-sidebar-mobile">
            <!-- Header -->
            <div class="card-header header-elements-inline">
                <h6 class="card-title">Main</h6>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <!-- /header -->
            <!-- User menu -->
            <div class="sidebar-user">
                <div class="card-body">
                    <div class="media">
                        <div class="mr-3">
                            <a href="#"><img src="{{ asset('backend/global_assets/images/fbbc0.jpg') }}" width="38" height="38" class="rounded-circle" alt=""></a>
                        </div>
                        <div class="media-body">
                            <div class="media-title font-weight-semibold">{{Auth::user()->fullname}}</div>
                            <div class="font-size-xs opacity-50">
                                <i style="color: green" class="icon-primitive-dot"></i> &nbsp;Online
                                {{-- /*<span style="color: green;font-size: 20px">•</span> Online*/ --}}
                            </div>
                        </div>
                        <div class="ml-3 align-self-center">
                            <a href="#" class="text-white"><i class="icon-cog3"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /user menu -->
            <!-- Main navigation -->
            <div class="card-body p-0">
                
                    <ul class="nav nav-sidebar" data-nav-type="accordion">
                        <!-- Main -->
                        <li class="nav-item">
                            <a href="{{ route('dashboard') }}" class="nav-link active">
                                <i class="icon-home4"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        {{-- <li class="nav-item ">
                            <a href="{{route('useradmin.index')}}" class="nav-link"><i class="icon-users"></i> <span>Account management</span></a>
                        </li> --}}
                        <li class="nav-item nav-item-submenu">
                            <a href="#" class="nav-link"><i class="icon-users"></i> <span>Account management</span></a>
                            <ul class="nav nav-group-sub" data-submenu-title="Tài khoản">
                                <li class="nav-item"><a href="{{route('useradmin.index')}}" class="nav-link">Staffs</a></li>
                                <li class="nav-item"><a href="{{route('client.index')}}" class="nav-link">Clients</a></li>
                            </ul>
                        </li>
                        <li class="nav-item ">
                            <a href="{{route('menu.index')}}" class="nav-link"><i class="icon-menu3"></i> <span>Menu</span></a>
                        </li>
                        <li class="nav-item ">
                            <a href="{{route('faq.index')}}" class="nav-link"><i class="icon-question3"></i> <span>FAQ</span></a>
                        </li>
                        <li class="nav-item ">
                            <a href="{{route('news.index')}}" class="nav-link"><i class="icon-stack"></i> <span>Tin Tức</span></a>
                        </li>
                        <li class="nav-item ">
                            <a id="menu_seen" href="{{route('lienhe.index')}}" class="nav-link"><i class="icon-phone"></i> <span>Liên hệ</span></a>
                        </li>   
                        <li class="nav-item"><a href="{{route('cauhinh.editNoId')}}" class="nav-link"><i class="icon-cog5"></i> <span>Setup</span></a></li>
                        <!-- /main -->
                    </ul>
              
            </div>
            <!-- /main navigation -->
        </div>
    </div>
    <!-- /sidebar content -->
</div>

resources/views/admin/blocks/script.blade.php
    <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
    
    <script> CKEDITOR.replace('editor1'); </script>

    <script> CKEDITOR.replace('editor2'); </script>

    <script> CKEDITOR.replace('editor3'); </script>

    <script> CKEDITOR.replace('editor4'); </script>

    <script> CKEDITOR.replace('editor5'); </script>
	<script>	
	function acceptDelete () {
   		if (window.confirm('Bạn chắc chắn muốn xóa?')) {
       		return true;
   		}
     		return false;
  	}
	</script>

resources/views/admin/blocks/sidebar.blade.php
<div class="navbar navbar-expand-md navbar-dark">
		<div class="navbar-brand wmin-200">
			<a href="{{route('dashboard')}}" class="d-inline-block">
				<img src="{{ asset('backend/global_assets/images/logoCPM.png') }}" alt="" style="height: 30px">
			</a>
		</div>

		<div class="d-md-none">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
				<i class="icon-tree5"></i>
			</button>
			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
				<i class="icon-paragraph-justify3"></i>
			</button>
		</div>

		<div class="collapse navbar-collapse" id="navbar-mobile">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
						<i class="icon-paragraph-justify3"></i>
					</a>
				</li>
			</ul>

			<ul class="navbar-nav ml-auto">

				<li class="nav-item dropdown dropdown-user">
					<a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
						<img src="{{ asset('backend/global_assets/images/fbbc0.jpg') }}" class="rounded-circle mr-2" height="34" alt="">
						<span>{{Auth::user()->username}}</span>
					</a>

					<div class="dropdown-menu dropdown-menu-right">
						<a href="{{route('useradmin.change-password')}}" class="dropdown-item"><i class="icon-key"></i>Change Password</a>	
						<div class="dropdown-divider"></div>
							<a href="{{ route('useradmin.edit',[Auth::user()->id]) }}" class="dropdown-item"><i class="icon-cog5"></i>Account settings</a>
							<a href="{{route('getLogout')}}" class="dropdown-item"><i class="icon-switch2"></i>Logout</a>
					</div>
				</li>
			</ul>
		</div>
	</div>