routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Admin')->group(function(){
	Route::get('sign-in','LoginController@getLogin')->middleware('loginal')->name('getLogin');
	Route::post('sign-in','LoginController@postLogin')->name('postLogin');
	Route::get('logout','LoginController@getLogout')->name('getLogout');

	Route::get('forgot-password', 'ResetPasswordController@getPassword')->name('getPassword');
	Route::post('forgot-password', 'ResetPasswordController@sendEmail')->name('sendEmail');
	Route::get('change-new-password', 'ResetPasswordController@getNewPassword')->name('getNewPassword');
	Route::post('change-new-password', 'ResetPasswordController@postNewPassword')->name('postNewPassword');
});
Route::namespace('Frontend')->group(function() {
	Route::get('','HomeController@index')->name('home');
	Route::get('bao-hiem-nhan-tho-cho-be-tre-em-con-tre-so-sinh','HomeController@GetBHNT')->name('bao-hiem-nhan-tho-cho-be-tre-em-con-tre-so-sinh');
	
	Route::get('gioi-thieu','HomeController@gioithieu')->name('gioi-thieu');
	Route::get('lien-he','HomeController@Getlienhe')->name('lien-he');
	Route::post('lien-he','HomeController@Postlienhe')->name('lien-he');
	Route::get('dieu-khoan-dich-vu','HomeController@dieukhoandichvu')->name('dieu-khoan-dich-vu');
	Route::get('chinh-sach-bao-mat','HomeController@chinhsachbaomat')->name('chinh-sach-bao-mat');
	Route::get('tu-van-mien-phi','HomeController@GetTuvan')->name('tu-van-mien-phi');
	Route::post('tu-van-mien-phi','HomeController@PostTuvan')->name('tu-van-mien-phi');
	Route::get('bai-viet','HomeController@GetNews')->name('bai-viet');
	Route::get('bai-viet-detail/{slug}','HomeController@GetNewsDetail')->name('bai-viet-detail');

	Route::post('tim-kiem','HomeController@search');
	
});

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){

	Route::get('dashboard','HomeController@index')->name('dashboard');

	Route::prefix('useradmin')->name('useradmin.')->group(function(){
		Route::get('index','UseradminController@index')->name('index');

		Route::get('add','UseradminController@create')->name('create');
		Route::post('add','UseradminController@store')->name('store');

		Route::get('edit/{id}','UseradminController@edit')->name('edit');
		Route::post('edit/{id}','UseradminController@update')->name('update');

		Route::get('change-password','UseradminController@Getchangepass')->name('change-password');
		Route::post('change-password','UseradminController@Postchangepass');

		Route::get('delete/{id}','UseradminController@destroy')->name('destroy');
	});
	Route::prefix('menu')->name('menu.')->group(function(){
		Route::get('index','MenuController@index')->name('index');

		Route::get('add','MenuController@create')->name('create');
		Route::post('add','MenuController@store')->name('store');

		Route::get('show-detail/{id}','MenuController@show')->name('show');

		Route::get('edit/{id}','MenuController@edit')->name('edit');
		Route::post('edit/{id}','MenuController@update')->name('update');

		Route::post('delete/{id}','MenuController@destroy')->name('destroy');
	});
	Route::prefix('lien-he')->name('lienhe.')->group(function(){
		Route::get('index','LienheController@index')->name('index');

		Route::get('add','LienheController@create')->name('create');
		Route::post('add','LienheController@store')->name('store');

		Route::get('show-detail/{id}','LienheController@show')->name('show');

		Route::get('edit/{id}','LienheController@edit')->name('edit');
		Route::post('edit/{id}','LienheController@update')->name('update');
		
		Route::post('delete/{id}','LienheController@destroy')->name('destroy');
	});
	Route::prefix('FAQ')->name('faq.')->group(function(){
		Route::get('index','FAQController@index')->name('index');

		Route::get('add','FAQController@create')->name('create');
		Route::post('add','FAQController@store')->name('store');

		Route::get('show-detail/{id}','FAQController@show')->name('show');

		Route::get('edit/{id}','FAQController@edit')->name('edit');
		Route::post('edit/{id}','FAQController@update')->name('update');
		
		Route::post('delete/{id}','FAQController@destroy')->name('destroy');
	});
	Route::prefix('tin-tuc')->name('news.')->group(function(){
		Route::get('index','NewsController@index')->name('index');

		Route::get('add','NewsController@create')->name('create');
		Route::post('add','NewsController@store')->name('store');

		Route::get('show-detail/{id}','NewsController@show')->name('show');

		Route::get('edit/{id}','NewsController@edit')->name('edit');
		Route::post('edit/{id}','NewsController@update')->name('update');
		
		Route::post('delete/{id}','NewsController@destroy')->name('destroy');
	});
	Route::prefix('client')->name('client.')->group(function(){
		Route::get('index','ClientController@index')->name('index');

		Route::get('add','ClientController@create')->name('create');
		Route::post('add','ClientController@store')->name('store');

		Route::get('show-detail/{id}','ClientController@show')->name('show');

		Route::get('edit/{id}','ClientController@edit')->name('edit');
		Route::post('edit/{id}','ClientController@update')->name('update');
		
		Route::post('delete/{id}','ClientController@destroy')->name('destroy');
	});
	
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
});

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreNews;
use App\Model\News;
use DateTime,DB;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $news;
    public function __construct(News $news)
    {
        $this->news = $news;
    }
    public function index()
    {
        $data['news'] = $this->news->ListNews();

        return view('admin.module.news.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.module.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreNews $req)
    {
        try {
            $data  = array(
                'title' => $req->title,
                'slug'      => (empty($req->slug))? str_slug($req->title,"-"):$req->slug,
                'intro' => $req->intro, 
                'content' => $req->content,
                'status' => $req->status,
                'created_at'    => new DateTime,
            );
        $this->news->storeNews($data);
        } catch (Exception $e) {
            return back()->with('alerterr','Wrong format');
        }
            return redirect()->back()->with('alertsuc','Thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['news'] = $this->news->editNews($id);

        return view('admin.module.news.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        try {
            $data  = array(
                'title' => $req->title,
                'slug'      => (empty($req->slug))? str_slug($req->name,"-"):$req->slug,
                'intro' => $req->intro, 
                'content' => $req->content,
                'status' => $req->status,
                'updated_at'    => new DateTime,
            );
        $this->news->updateNews($data,$id);
        } catch (Exception $e) {
            return back()->with('alerterr','Wrong format');
        }
            return redirect()->back()->with('alertsuc','Thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        $data = $req->input('checked',[]);

        for ($i=0; $i < count($data) ; $i++) { 
             $this->news->delNews($data[$i]);
        }
        return redirect()->route('news.index')->with('alertsuc','Xóa thành công');
    }
}

resources/views/admin/module/news/create.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('news.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Thêm</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Add News</h5>              
            </div>
            <div class="card-body">
                <form action="{{ route('news.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-12">
                            <label class="lable_edit">Tiêu đề <span class="text-danger">*</span></label>
                            <input value="{{old('title')}}" type="text" name="title" class="form-control" required="" >
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">                        
                        <div class="col-sm-6">
                            <label class="lable_edit">Mô tả ngắn <span class="text-danger">*</span></label>
                            <textarea rows="1" class="form-control" name="intro" placeholder="Mô tả ngắn">{{old('intro')}}</textarea>
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Trạng thái <span class="text-danger">*</span></label>
                            <select name="status" class="form-control">
                                <option value="0">Chưa duyệt bài</option>
                                <option value="1">Đã duyệt bài</option>
                            </select>
                        </div>
                        
                    </div>
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-12">                        
                            <label class="lable_edit">Nội dung <span class="text-danger">*</span></label>
                            <textarea rows="1" id="editor1" class="form-control" name="content" placeholder="Nội dung">{{old('content')}}</textarea>
                        </div>
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/news/edit.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('news.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Update</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Update News</h5>              
            </div>
            <div class="card-body">
                <form action="{{ route('news.update',['id'=> $news->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-12">
                            <label class="lable_edit">Tiêu đề <span class="text-danger">*</span></label>
                            <input value="{{old('title',$news->title)}}" type="text" name="title" class="form-control" required="" >
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">                        
                        <div class="col-sm-6">
                            <label class="lable_edit">Mô tả ngắn <span class="text-danger">*</span></label>
                            <textarea rows="1" class="form-control" name="intro" placeholder="Mô tả ngắn">{{old('intro',$news->intro)}}</textarea>
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Trạng thái <span class="text-danger">*</span></label>
                            <select name="status" class="form-control">
                                <option value="0" {{$news->status == 0 ? 'selected' : ''}}>Chưa duyệt bài</option>
                                <option value="1" {{$news->status == 1 ? 'selected' : ''}}>Đã duyệt bài</option>
                            </select>
                        </div>
                        
                    </div>
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-12">                        
                            <label class="lable_edit">Nội dung <span class="text-danger">*</span></label>
                            <textarea rows="1" id="editor1" class="form-control" name="content" placeholder="Nội dung">{{old('content',$news->content)}}</textarea>
                        </div>
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/news/index.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('news.index')}}" class="breadcrumb-item">Danh sách</a>
                {{-- <span class="breadcrumb-item active">Current</span> --}}
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="content-wrapper">
    @include('admin.blocks.alert')
    <div class="content">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">List News</h5>               
            </div>

            <div class="card-body">
                <div class="product-status-wrap">
                    <div class="form-group">
                        <a class="btn btn-success" href="{{ route('news.create') }}">ADD</a>
                    </div>  
                     <form action="{{route('news.destroy',['action' => 'delete'])}}" name="listForm" id="listForm" method="POST" >
                        @csrf            
                        <div class="table-responsive-sm form-group">
                            <table class="table table-sm table-striped table-bordered">
                                <thead>
                                    <tr >
                                        <th scope="col">
                                            <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                                        </th>
                                        <th scope="col">ID</th>
                                        <th scope="col">Tiêu đề</th>                                       
                                        <th scope="col">Mô tả ngắn</th>
                                        <th scope="col">Trạng thái</th>
                                        <th scope="col">Hoạt động</th>                                      
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($news as $item)
                                    <tr>
                                        <td >
                                            <input value="{{ $item->id }}"  type="checkbox" name="checked[]">         
                                        </td>
                                        <td>{{$item->id}}</td>
                                        <td>{{$item->title}}</td>
                                        <td>{{$item->intro}}</td>
                                        <td>
                                           
                                            <label class="switch-light" onclick="">
                                                <input id="changestatus" type="checkbox" {{ $item->status ? 'checked' : ''}} data-id="{{$item->id}} ">
                                                <span class="well" style="font-size: 80%">
                                                    <span>Disable</span>
                                                    <span>Enable</span>
                                                    <a class="btn btn-primary"></a>
                                                </span>
                                             </label>
                                        </td>                                        
                                        <td>
                                            {{convertdate($item->created_at)}}
                                        </td>
                                        <td style="text-align: center;">
                                            <a href="{{ route('news.edit', ['news' => $item->id]) }}" data-toggle="tooltip" title="Sửa" class="pd-setting-ed">
                                                <i class="icon-pencil7" aria-hidden="true"></i>
                                            </a>
                                        </td>                   
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group row">
                            <button onclick="return acceptDelete()" type="submit" data-toggle="tooltip" title="Xóa" class="btn btn-danger">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                            <div style="position: absolute;right: 20px">
                                {{$news->links()}}
                            </div>
                        </div>
                    
                    </form>
                     
                     
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function () {
    $('.switch-light #changestatus').on('click',function () {
        var Id = $(this).data('id');
        var status = this.checked;
        $.ajax({
            type: "POST",
            url: "../../api/change-status-tintuc",
            data: {
                id: Id,
                status: status,
            },
            success: function (dd) {  
            },
            error: function () {
            }
        })
    });
});
</script> 
@endsection