routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Admin')->group(function(){
	Route::get('sign-in','LoginController@getLogin')->middleware('loginal')->name('getLogin');
	Route::post('sign-in','LoginController@postLogin')->name('postLogin');
	Route::get('logout','LoginController@getLogout')->name('getLogout');

	Route::get('forgot-password', 'ResetPasswordController@getPassword')->name('getPassword');
	Route::post('forgot-password', 'ResetPasswordController@sendEmail')->name('sendEmail');
	Route::get('change-new-password', 'ResetPasswordController@getNewPassword')->name('getNewPassword');
	Route::post('change-new-password', 'ResetPasswordController@postNewPassword')->name('postNewPassword');
});
Route::namespace('Frontend')->group(function() {
	Route::get('','HomeController@index')->name('home');
	Route::get('bao-hiem-nhan-tho-cho-be-tre-em-con-tre-so-sinh','HomeController@GetBHNT')->name('bao-hiem-nhan-tho-cho-be-tre-em-con-tre-so-sinh');
	
	Route::get('gioi-thieu','HomeController@gioithieu')->name('gioi-thieu');
	Route::get('lien-he','HomeController@Getlienhe')->name('lien-he');
	Route::post('lien-he','HomeController@Postlienhe')->name('lien-he');
	Route::get('dieu-khoan-dich-vu','HomeController@dieukhoandichvu')->name('dieu-khoan-dich-vu');
	Route::get('chinh-sach-bao-mat','HomeController@chinhsachbaomat')->name('chinh-sach-bao-mat');
	Route::get('tu-van-mien-phi','HomeController@GetTuvan')->name('tu-van-mien-phi');
	Route::post('tu-van-mien-phi','HomeController@PostTuvan')->name('tu-van-mien-phi');
	Route::get('bai-viet','HomeController@GetNews')->name('bai-viet');
	Route::get('bai-viet-detail/{slug}','HomeController@GetNewsDetail')->name('bai-viet-detail');

	Route::post('tim-kiem','HomeController@search');
	
});

Route::namespace('Admin')->middleware('login')->prefix('admin')->group(function(){

	Route::get('dashboard','HomeController@index')->name('dashboard');

	Route::prefix('useradmin')->name('useradmin.')->group(function(){
		Route::get('index','UseradminController@index')->name('index');

		Route::get('add','UseradminController@create')->name('create');
		Route::post('add','UseradminController@store')->name('store');

		Route::get('edit/{id}','UseradminController@edit')->name('edit');
		Route::post('edit/{id}','UseradminController@update')->name('update');

		Route::get('change-password','UseradminController@Getchangepass')->name('change-password');
		Route::post('change-password','UseradminController@Postchangepass');

		Route::get('delete/{id}','UseradminController@destroy')->name('destroy');
	});
	Route::prefix('menu')->name('menu.')->group(function(){
		Route::get('index','MenuController@index')->name('index');

		Route::get('add','MenuController@create')->name('create');
		Route::post('add','MenuController@store')->name('store');

		Route::get('show-detail/{id}','MenuController@show')->name('show');

		Route::get('edit/{id}','MenuController@edit')->name('edit');
		Route::post('edit/{id}','MenuController@update')->name('update');

		Route::post('delete/{id}','MenuController@destroy')->name('destroy');
	});
	Route::prefix('lien-he')->name('lienhe.')->group(function(){
		Route::get('index','LienheController@index')->name('index');

		Route::get('add','LienheController@create')->name('create');
		Route::post('add','LienheController@store')->name('store');

		Route::get('show-detail/{id}','LienheController@show')->name('show');

		Route::get('edit/{id}','LienheController@edit')->name('edit');
		Route::post('edit/{id}','LienheController@update')->name('update');
		
		Route::post('delete/{id}','LienheController@destroy')->name('destroy');
	});
	Route::prefix('FAQ')->name('faq.')->group(function(){
		Route::get('index','FAQController@index')->name('index');

		Route::get('add','FAQController@create')->name('create');
		Route::post('add','FAQController@store')->name('store');

		Route::get('show-detail/{id}','FAQController@show')->name('show');

		Route::get('edit/{id}','FAQController@edit')->name('edit');
		Route::post('edit/{id}','FAQController@update')->name('update');
		
		Route::post('delete/{id}','FAQController@destroy')->name('destroy');
	});
	Route::prefix('tin-tuc')->name('news.')->group(function(){
		Route::get('index','NewsController@index')->name('index');

		Route::get('add','NewsController@create')->name('create');
		Route::post('add','NewsController@store')->name('store');

		Route::get('show-detail/{id}','NewsController@show')->name('show');

		Route::get('edit/{id}','NewsController@edit')->name('edit');
		Route::post('edit/{id}','NewsController@update')->name('update');
		
		Route::post('delete/{id}','NewsController@destroy')->name('destroy');
	});
	Route::prefix('client')->name('client.')->group(function(){
		Route::get('index','ClientController@index')->name('index');

		Route::get('add','ClientController@create')->name('create');
		Route::post('add','ClientController@store')->name('store');

		Route::get('show-detail/{id}','ClientController@show')->name('show');

		Route::get('edit/{id}','ClientController@edit')->name('edit');
		Route::post('edit/{id}','ClientController@update')->name('update');
		
		Route::post('delete/{id}','ClientController@destroy')->name('destroy');
	});
	
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
});

app/Http/Controllers/Admin/LienheController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Lienhe;
use DateTime;

class LienheController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $lienhe;
    public function __construct(Lienhe $lienhe)
    {
        $this->lienhe = $lienhe;
    }
    public function index()
    {
        $data['lienhe'] = $this->lienhe->ListLienhe();

        return view('admin.module.lienhe.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.module.lienhe.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['lienhe'] = $this->lienhe->editLienhe($id);

        return view('admin.module.lienhe.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
         try {
             $data = array(
                        'name' => $req->name,
                        'phone' => $req->phone,
                        'message' => $req->message,
                        'updated_at'    => new DateTime,
                    ); 
           
            $this->lienhe->updateLienhe($data,$id);
            
        } catch (Exception $e) {
            
            return back()->with('alerterr','Wrong format');
        }
            return redirect()->back()->with('alertsuc','Thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        $data = $req->input('checked',[]);

        for ($i=0; $i < count($data) ; $i++) { 
             $this->lienhe->delLienhe($data[$i]);
        }
        return redirect()->route('lienhe.index')->with('alertsuc','Xóa thành công');
    }
}

resources/views/admin/module/lienhe/create.blade.php
{{-- @extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('lienhe.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">ADD</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">ADD Contact</h5>              
            </div>
            <div class="card-body">
                <form action="{{ route('lienhe.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Tên User <span class="text-danger">*</span></label>
                            <input value="{{old('name')}}" type="text" name="name" class="form-control" required="" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Email <span class="text-danger">*</span></label>
                            <input value="{{old('email')}}" type="email" name="email" class="form-control" required="" >
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">                        
                        <div class="col-sm-6">
                            <label class="lable_edit">Mô tả ngắn <span class="text-danger">*</span></label>
                            <textarea rows="1" class="form-control" name="message" placeholder="Mô tả ngắn">{{old('message')}}</textarea>
                        </div>
                      
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection --}}

resources/views/admin/module/lienhe/edit.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('lienhe.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Cập nhật</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Update Contact</h5>              
            </div>
            <div class="card-body">
                <form action="{{ route('lienhe.update',['id' => $lienhe->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Tên User <span class="text-danger">*</span></label>
                            <input value="{{old('name',$lienhe->name)}}" type="text" name="name" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Phone <span class="text-danger">*</span></label>
                            <input value="{{old('phone',$lienhe->phone)}}" type="number" name="phone" class="form-control">
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">                        
                        <div class="col-sm-6">
                            <label class="lable_edit">Mô tả ngắn <span class="text-danger">*</span></label>
                            <textarea rows="1" class="form-control" name="message" placeholder="Mô tả ngắn">{{old('message',$lienhe->message)}}</textarea>
                        </div>
                      
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Cập nhật
                        </button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/lienhe/index.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('dashboard')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('lienhe.index')}}" class="breadcrumb-item">Danh sách</a>
                {{-- <span class="breadcrumb-item active">Current</span> --}}
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="content-wrapper">
    @include('admin.blocks.alert')
    <div class="content">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">List Contact</h5>                
            </div>
            <div class="card-body">
                <div class="product-status-wrap">
                   
                    <form action="{{route('lienhe.destroy',['action' => 'delete'])}}" name="listForm" id="listForm" method="POST" >
                        @csrf
                        <div class="table-responsive-sm form-group">
                            <table class="table table-sm table-striped table-bordered">
                                <thead>
                                    <tr >
                                        <th scope="col">
                                            <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                                        </th>
                                        <th scope="col">ID</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Phone</th>
                                        <th scope="col">Message</th>
                                        <th scope="col">Created date</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($lienhe as $item)
                                    <tr>
                                        <td >
                                            <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                                        </td>
                                        <td>{{$item->id}}</td>
                                        <td>{{$item->name}}</td>
                                        <td>{{$item->phone}}</td>
                                        <td>{{$item->message}}</td>
                                        <td>{{ date("d/m/Y-H:i:s",strtotime($item ->created_at))}}</td>
                                        <td style="text-align: center;">
                                            <a href="{{ route('lienhe.edit', ['lienhe' => $item->id]) }}" data-toggle="tooltip" title="Edit" class="pd-setting-ed">
                                                <i class="icon-pencil7" aria-hidden="true"></i>
                                            </a>  
                                        </td>                   
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group row">
                            <button onclick="return acceptDelete()" type="submit" data-toggle="tooltip" title="Xóa" class="btn btn-danger">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                            <div style="position: absolute;right: 20px">
                                {{$lienhe->links()}}
                            </div>
                        </div>
                     </form>                     
                </div>
            </div>
        </div>
    </div>
</div>
@endsection